enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Enable slide to seek' 'Remove player controls background' 'Change header' 'Custom branding'"
version = "auto"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
included-patches = "'Permanent shuffle' 'Permanent repeat' 'Compact header'"
build-mode = "both"
arch = "both"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"