enable-magisk-update = true

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change header' 'Custom branding'"
excluded-patches = "'Theme'"
version = "auto"
build-mode = "both"

[YouTube-Extended]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Custom branding heading' 'Custom branding icon YouTube' 'MaterialYou' 'Settings icons'"
excluded-patches = "'Theme'"
version = "auto"
build-mode = "both"
app-name = "YouTube"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
build-mode = "both"
arch = "both"

[Music-Extended]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Custom branding icon YouTube Music' 'Replace cast button'"
version = "latest"
build-mode = "both"
arch = "both"
app-name = "Music"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-Extended]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Change package name'"
app-name = "Reddit"

[X]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
included-patches = "'Hide For You' 'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons'"
build-mode = "apk"

[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
