logging-to-file = true
enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Add splash animation' 'Enable song search' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide player button background' 'Hide voice search button' 'MaterialYou' 'Premium heading' 'Shorts outline button'"
excluded-patches = "'Custom branding name YouTube' 'Theme'"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Disable overlay filter' 'Enable old player layout' 'Hide double tap overlay filter' 'Hide player overlay filter' 'Hide voice search button' 'Replace cast button'"
excluded-patches = "'Custom branding name YouTube Music'"
build-mode = "both"
arch = "both"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Change package name'"

[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"