enable-magisk-update = true

[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Change header' 'Custom branding'"
excluded-patches = "'Theme'"
version = "auto"
build-mode = "both"

[YouTube-Extended]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
version = "auto"
build-mode = "both"
app-name = "YouTube"

[Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
version = "auto"
build-mode = "both"
arch = "both"

[Music-Extended]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Replace cast button'"
version = "6.50.51"
build-mode = "both"
arch = "both"
app-name = "Music"

[Reddit-Extended]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Change package name' 'Custom branding name Reddit'"
app-name = "Reddit"

[X]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Hide promote button' 'Force enable translate' 'Hide Community Notes' 'Hide FAB' 'Customize profile tabs' 'Disable chirp font' 'Add ability to copy media link'"
build-mode = "apk"

[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
