logging-to-file = true
enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Add splash animation' 'Custom branding icon Revancify Red' 'Enable music search' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide player button background' 'MaterialYou' 'Premium heading' 'Shorts outline button'"
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube' 'Theme'"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Custom branding icon Revancify Red' 'Enable old player layout' 'Replace cast button'"
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube Music'"
build-mode = "both"
apkmirror-arch = "both"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[X]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[TikTok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"
