enable-magisk-update = true

[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Enable slide to seek' 'Remove player controls background' 'Change header' 'Custom branding'"
version = "auto"
build-mode = "both"

[Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
included-patches = "'Permanent repeat'"
build-mode = "both"
arch = "both"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[X]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "apk"

[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"